target-version = "py39"
indent-width = 4
line-length = 120

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"
avoid-escape = true

[lint]
# See complete list: https://docs.astral.sh/ruff/rules/
select = [
    "I",  # isort
    "E",  # pycodestyle
    "W",  # pycodestyle
    "B",  # bugbear
    "F",  # pyflakes
    "UP", # pyupgrade
    "RUF", # ruff
    "PL", # pylint
    "Q", # flake8-quotes
]
fixable = [
    "I",  # isort
    "UP035", # deprecated import
    "RUF022", # `__all__` is not sorted
    "Q000",  # bad quotes inline string
    "Q001",  # bad quotes multiline string
    "Q002",  # bad quotes docstring
    "Q003",  # avoidable escaped quote
    "Q004",  # unnecessary escaped quote
]
ignore = [
    "E501", # line too long
    "PLC0415", # import outside top level
    "PLR0911", # too many return statements
    "PLR0912", # too many branches
    "PLR0913", # too many arguments
    "PLR0915", # too many statements
    "PLR2004", # magic value comparison
    "PLW0603", # global statement
    "RUF001", # ambiguous character
]